name: BUILD APK

on:
 # push:
  #  branches: [ APK ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: game-ci/unity-builder@v2.0.4
        env:
           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE}}
        with:
            targetPlatform: Android
            buildMethod: Build.APK
      - uses: actions/upload-artifact@v3
        with:
          name: Build-Android
          path: build/Android
